from .complementarias import *
from .datos_de_entrada import *
from .logica import *
from .grafica import *
from .validaciones import *
from .vida_llena import *
from .boton import *
from .texto import *
from .ranking import *
from graficos import config